apiVersion: apps/v1  # 指定api版本，此值必须在kubectl api-versions中
kind: Deployment  # 指定创建资源的角色/类型
metadata:  # 资源的元数据/属性
  name: test-module-deployment-non-peer  # 资源的名字，在同一个namespace中必须唯一
  namespace: default # 部署在哪个namespace中
  labels:  # 设定资源的标签
    deployment.koupleless.io/deployment0: 0.1.0
spec: # 资源规范字段
  replicas: 1
  revisionHistoryLimit: 3 # 保留历史版本
  selector: # 选择器
    matchLabels: # 匹配标签
      app: test-module-deployment-non-peer
  strategy: # 策略
    rollingUpdate: # 滚动更新
      maxSurge: 30% # 最大额外可以存在的副本数，可以为百分比，也可以为整数
      maxUnavailable: 30% # 示在更新过程中能够进入不可用状态的 Pod 的最大值，可以为百分比，也可以为整数
    type: RollingUpdate # 滚动更新策略
  template: # 模版
    metadata: # 资源的元数据/属性
      labels: # 设定资源的标签
        module-controller.koupleless.io/component: module # 必要，声明pod的类型，用于module controller管理
        module.koupleless.io/name: bizName
        module.koupleless.io/version: bizVersion
        # deployment unique id
        app: test-module-deployment-non-peer
    spec: # 资源规范字段
      containers:
        - name: bizName
          image: https://serverless-opensource.oss-cn-shanghai.aliyuncs.com/module-packages/stable/bizName-bizVersion-ark-biz.jar
          env:
            - name: BIZ_VERSION
              value: bizVersion
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: base.koupleless.io/stack
                    operator: In
                    values:
                      - java # 多语言环境下可能有其他技术栈
                  - key: base.koupleless.io/version
                    operator: In
                    values:
                      - 1.1.1 # 模块可能只能被调度到一些特殊版本的 node 上，如有这种限制，则必须有这个字段。
                  - key: base.koupleless.io/name
                    operator: In
                    values:
                      - base  # 模块可能只能被调度到一些特殊版本的 node 上，如有这种限制，则必须有这个字段。
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: topology.kubernetes.io/zone
              labelSelector:
                - matchExpressions:
                    - key: module.koupleless.io/name
                      operator: In
                      values:
                        - bizName
                    - key: module.koupleless.io/version
                      operator: In
                      values:
                        - bizVersion
      tolerations:
        - key: "schedule.koupleless.io/virtual-node"
          operator: "Equal"
          value: "True"
          effect: "NoExecute"