apiVersion: v1
kind: Pod
metadata:
  name: test-base-pod
  namespace: default
spec:
  containers:
    - image: anolis-registry.cn-zhangjiakou.cr.aliyuncs.com/openanolis/nginx:1.14.1-8.6
      imagePullPolicy: IfNotPresent
      name: test-pod-container
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
  dnsPolicy: ClusterFirst
  schedulerName: default-scheduler
  terminationGracePeriodSeconds: 30